### ISSUE TITLE
no errors in tolerant mode

### ISSUE THREAD

**Issue by nowindowsowrking** [jquery/esprima#1766] opened 2017-02-26 10:52 UTC
```js
"\1"; "use strict";
```
Does output an empty array without any error messages, but the error message should  
`Line 1: Octal literals are not allowed in strict mode.`

Also this combinations does not show any errors:

```js
function hello() { "octal directive\1"; "use strict"; }
"use strict"; x = { set f(eval) {} }
```

**Comment by nowindowsowrking** [comment] 2017-02-26 11:08
Here is an example where no error are visible

**Code in:** `var x = /[P QR]/\g`

**Output:** 

```js
{
        "body": [
          {
            "declarations": [
              {
                "id": {
                  "name": "x",
                  "type": "Identifier"
                },
                "init": {
                  "raw": "/[P QR]/g",
                  "regex": {
                    "flags": "g",
                    "pattern": "[P QR]"
                  },
                  "type": "Literal",
                  "value": /[P QR]/g
                },
                "type": "VariableDeclarator"
              }
            ],
            "kind": "var",
            "type": "VariableDeclaration"
          }
        ],
        "errors": [],  // No errors here!!
        "sourceType": "script",
        "type": "Program"
      }
```

**Comment by ariya** [comment] 2017-02-26 18:49
Thanks for the report @nowindowsowrking! Please try to keep it one problem at a time. Also, please include the steps to reproduce the problem.

Here's what I tried, both did not reproduce the problem you're describing. The code parsed by Esprima correctly triggered the error.

```js
> esprima.parse('"\\1"; "use strict"', { tolerant: true }).errors.length
1
> esprima.parse('var x = /[P QR]/\\g', { tolerant: true }).errors.length
1
```

**Comment by nowindowsowrking** [comment] 2017-02-27 05:11
@ariya I am on Windows 10 and NodejS v. 7.5.0, and I simply did this 

```js
esprima.parse('var x = /[P QR]/\g', { tolerant: true})
```

I also tried it with `esprima.parseModule` and `esprima.parseScript`   with same result.

**Comment by ariya** [comment] 2017-02-27 05:15
@nowindowsowrking The backslash needs to be escaped with another backslash.

**Comment by nowindowsowrking** [comment] 2017-02-27 05:18
@ariya I know. But if I do that and run the same test, I ending up with `Error: Line 1: Unexpected token ILLEGAL`  
It seems there are unicode, regular expressions that are the issue here except for this one `1 = 2`

**Comment by nowindowsowrking** [comment] 2017-02-27 05:24
@ariya Here is part of the stack trace if that helps
```js
1) Testing tolerant mode
     Error: Line 1: Unexpected token ILLEGAL
      at ErrorHandler.constructError (esprima.js:826:21)
      at ErrorHandler.createError (esprima.js:842:26)
      at ErrorHandler.throwError (esprima.js:849:20)
      at Scanner.throwUnexpectedToken (esprima.js:961:34)
      at Scanner.scanPunctuator (esprima.js:1480:18)
      at Scanner.lex (esprima.js:2095:21)
      at Parser.nextToken (esprima.js:2357:33)
      at Parser.nextRegexToken (esprima.js:2381:14)
      at Parser.parsePrimaryExpression (esprima.js:2632:38)
      at Parser.inheritCoverGrammar (esprima.js:2556:36)
      at Parser.parseLeftHandSideExpressionAllowCall (esprima.js:3219:25)
      at Parser.inheritCoverGrammar (esprima.js:2556:36)
      at Parser.parseUpdateExpression (esprima.js:3329:25)
      at Parser.parseUnaryExpression (esprima.js:3373:25)
      at Parser.inheritCoverGrammar (esprima.js:2556:36)
      at Parser.parseExponentiationExpression (esprima.js:3379:25)
      at Parser.inheritCoverGrammar (esprima.js:2556:36)
      at Parser.parseBinaryExpression (esprima.js:3416:25)
      at Parser.inheritCoverGrammar (esprima.js:2556:36)
      at Parser.parseConditionalExpression (esprima.js:3465:25)
      at Parser.parseAssignmentExpression (esprima.js:3580:25)
      at Parser.isolateCoverGrammar (esprima.js:2540:36)
      at Parser.parseVariableDeclaration (esprima.js:3964:25)
      at Parser.parseVariableDeclarationList (esprima.js:3976:24)
      at Parser.parseVariableStatement (esprima.js:3986:33)
```

**Comment by ariya** [comment] 2017-02-27 14:48
@nowindowsowrking What's the result of running this on your Node.js REPL?
```js
> esprima = require('esprima');
> esprima.parse('var x = /[P QR]/\\g', { tolerant: true }).errors
```

**Comment by ariya** [comment] 2017-02-27 14:50
@nowindowsowrking Unfortunately, your report tends to be confusing and ambiguous.
Do me a favor and carefully read this wiki page:

https://github.com/jquery/esprima/wiki/Filing-a-Defect

and then explain the situation again by strictly following the said pattern (test case, actual, expected).

**Comment by nowindowsowrking** [comment] 2017-02-28 06:08
@ariya To say it easy. I experience same issues as mentioned in this ticket https://github.com/jquery/esprima/issues/1772

**Comment by ariya** [comment] 2017-03-27 01:40
Closing, due to lack of confirmation (see backslash escaping above).

**Closed by ariya** 2017-03-27 01:40 UTC
