### ISSUE TITLE
Wrong parsing of function returning a multi-line template string

### ISSUE THREAD

**Issue by AurelienRibon** [jquery/esprima#1869] opened 2017-10-24 10:13 UTC
### Steps to reproduce

Parse the following script:
```js
function foo() {
  return `a
  b`;
}
```

### Actual output

Here is the body of the `FunctionDeclaration` item:
```
{
    "type": "BlockStatement",
    "body": [
        {
            "type": "ReturnStatement",
            "argument": null                    <------------ ???
        },
        {
            "type": "ExpressionStatement",
            "expression": {
                "type": "TemplateLiteral",
                "quasis": [
                    {
                        "type": "TemplateElement",
                        "value": {
                            "raw": "a\n  b",
                            "cooked": "a\n  b"
                        },
                        "tail": true
                    }
                ],
                "expressions": []
            }
        }
    ]
}
```

### Expected output
The `ReturnStatement` item should not have a `null` argument, but the `TemplateLiteral` that appears as the next statement.

**Comment by ariya** [comment] 2017-11-20 02:23
Thanks for the report @AurelienRibon! I believe this is a duplicate of #1829.

**Closed by ariya** 2017-11-20 02:23 UTC

**Comment by AurelienRibon** [comment] 2017-11-20 14:06
Thanks for fixing it! 👍
