### ISSUE TITLE
Document not updated

### ISSUE THREAD

**Issue by jiyinyiyong** [jquery/esprima#1156] opened 2015-03-29 07:25 UTC
For properties, the document says:
https://developer.mozilla.org/en-US/docs/Mozilla/Projects/SpiderMonkey/Parser_API
```
interface Property <: Node {
    type: "Property";
    key: Literal | Identifier;
    value: Expression;
    kind: "init" | "get" | "set";
}
```
while the parser gives:
http://esprima.org/demo/parse.html
```json
{
    "type": "Program",
    "body": [
        {
            "type": "ExpressionStatement",
            "expression": {
                "type": "ObjectExpression",
                "properties": [
                    {
                        "type": "Property",
                        "key": {
                            "type": "Identifier",
                            "name": "prop"
                        },
                        "computed": true,
                        "value": {
                            "type": "Literal",
                            "value": 1,
                            "raw": "1"
                        },
                        "kind": "init",
                        "method": false,
                        "shorthand": false
                    }
                ]
            }
        }
    ]
}
```

could you update the docs or give some test cases that people may refer to?

**Comment by nzakas** [comment] 2015-03-29 15:09
Thanks for the comment. It's not obvious, but the spec has been moved to a separate repo and is being updated for ES6. Please refer to https://github.com/estree/estree/blob/master/es6.md for this definition.

**Comment by mikesherov** [comment] 2015-03-30 01:09
In the future, once the estree spec stabilizes, the MDN entry will have a prominent message pointing to the new spec. Either way, this is not a bug in esprima itself, so closing this as as-expected.

**Closed by mikesherov** 2015-03-30 01:09 UTC
Labels: as-expected

**Comment by jiyinyiyong** [comment] 2015-03-30 02:25
Thanks. I'd like to watch `estree` for updates.
