### ISSUE TITLE
Esprima doesn't fail according to TC39

### ISSUE THREAD

**Issue by nowindowsowrking** [jquery/esprima#1760] opened 2017-02-25 14:54 UTC
Esprima should throw on this combinations

```js
while(true) function a(){}
with(true) function a(){}
for(a in b) function c(){}
for(;;) function a(){}
for(([a]) in 0);
[([a])] = 12;
for(({a}) in 0);
function* l() { ([e=yield])=>12 };
for(var x=1 in [1,2,3]) 0
with(true) class a {}
"use strict"; ({ v: eval }) = obj
({a: (b = 0)} = {})
(([a])=0);
for(({a}) of 0);
([a])--
[...a=12]=12
async(s=await)=>l
while (false)foo:if(false)continue foo;
for (var [a];;) break;
try {} catch (a) { for (var a of l) break;}
"use strict"; 08
function l([a,a]) {}
while (false) function l() {}
[([a])] = 12;
function* l() { ([e=yield])=>12 };
({a,...b}) => 0;
[(a = 0)] = 1
({a:(b = 0)} = 1)
```

**Comment by mikesherov** [comment] 2017-02-25 15:56
Thanks for contributing! Would it be possible for you to break these down into individual issues based upon root cause? These kinds of tickets, hike ultimately helpful, always end up closed with 4 or 5 issues behind it.

If not, that's ok too.

**Comment by nowindowsowrking** [comment] 2017-02-26 14:32
@mikesherov Not sure how I can break this down into individual issues because I randomly testested Esprima against [TC39 parser tests (*failing*](https://github.com/tc39/test262-parser-tests/tree/master/fail). As you may see if you click on the link, all tests have numbers.

**Comment by ariya** [comment] 2017-02-26 14:52
@nowindowsowrking Thanks for the report! Unfortunately, bulk reporting like this places too much burden in subsequent triaging (some issues are known for compatibilities, some are already files as defect reports, some others require a deeper discussion).
The best way to do this is to integrate the test262-parser into the project. Any failing tests can be marked as XFAIL for further follow-up and analysis.

**Comment by nowindowsowrking** [comment] 2017-02-26 15:40
@ariya  If test262-parser integration, I fear it will end up with tons of different issue tickets, so maybe best the project owner do that. Because I was checking various combinations, and I was surprised to find out that Esprimas only weak point mostly seems to combinations that should fail. The other way around allmost everything passes after the specs.

As an easy start to solve "failing issues" is to take a look at Acorns latest 3 commits. They solved now some of the issues that Esprima fails on, and are the majority of the TC39 failing test issues.

And this again leads to Annex B integration. Something I guess belong to another issue ticket.

**Comment by ariya** [comment] 2017-03-04 15:55
We're just going to fold this into #1773.

**Closed by ariya** 2017-03-04 15:55 UTC
