### ISSUE TITLE
Invalid left-hand side in assignment - 

### ISSUE THREAD

**Issue by nowindowsowrking** [jquery/esprima#1810] opened 2017-03-28 02:59 UTC
@ariya I noticed that Esprima have a lot of LHS issues, and many of this issues has exist for years. And some of this errors are early errors such as `12.14.1 - Invalid left-hand side in assignment`. 

This is a few that Esprima breaks on.

```js
({a}) = 0;
for(({a}) in 0);
[a, ...(b = c)] = 0
({x, y}) = {}
({Object = 0, String = 0}) = {};
({a:(b = 0)} = 1)
[(a = 0)] = 1
'use strict'; ({ v: eval }) = obj
'use strict'; ({ v: arguments }) = obj
({a:(b = 0)} = 1)
({a:(b = 0)} = 1)
// 12.14.1 - Invalid left-hand side in assignment

```
I will put an end to all this shortly, and follow up this issue ticket with a solution that solves this. I need to verify that I did everything correct in my end first!

**Comment by nowindowsowrking** [comment] 2017-03-28 03:15
@ariya I verified it, so here we go. This is just a start., and you would need to adjust it yourself. At least you can close some issue tickets.

The specs says this `12.3.1.6Static Semantics: IsValidSimpleAssignmentTarget`

Create this function to start with

```js
 // This need to be extended further. See ECMA specs
function isValidSimpleAssignmentTarget(node: any): boolean {
  if (node == null) {
       return false; 
  }
  switch (node.type) {
    case "Identifier":
    case "ComputedMemberExpression":
    case "StaticMemberExpression":
      return true;
  }
  return false;
}
```
In parseGroupingExpression, replace [this line](https://github.com/jquery/esprima/blob/master/src/parser.ts#L1133) with

```js
   this.context.isBindingElement = false;
  
  if (!isValidSimpleAssignmentTarget(expr)) {
      this.context.isAssignmentTarget = false;
  }
```

**Comment by nowindowsowrking** [comment] 2017-03-28 05:16
@ariya Also study `12.2.1.5Static Semantics: IsValidSimpleAssignmentTarget`

Quote:
 ```js
PrimaryExpression : CoverParenthesizedExpressionAndArrowParameterList

1. Let expr be CoveredParenthesizedExpression of CoverParenthesizedExpressionAndArrowParameterList.
2. Return IsValidSimpleAssignmentTarget of expr.
```
There are a few other places where you should check for the same thing - `parseAssignmentExpression` and `parseUnaryExpression`

**Comment by ariya** [comment] 2017-03-28 11:01
Thanks for the report!

@nowindowsowrking It's correct that this problem "has exist for years". It's because nobody comes forward to fix it yet (this project is supported by its volunteers, it's not a commercial software). I'm not sure what you want to achieve by always mentioning it again and again and again.

**Comment by mikesherov** [comment] 2017-03-28 11:50
To be clear, @nowindowsowrking, we really appreciate you reporting defects and taking an interest in the project, but you may want to consider that the tone of voice and words you are choosing to use when describing the issue can be seen as discouraging and insulting to the maintainers of the project. This may be unintentional, but I just wanted to point it out so we can all move forward successfully.

**Comment by nowindowsowrking** [comment] 2017-03-28 14:09
@ariya @mikesherov I get the point. Let's start all over with a normal tone. So you both know. I'm that kind of person that get things done, but not so talkative. I noticed a pile of unsolved issues, and when I kept reporting defects it got even bigger. That said. I decided to try to solve all current issues on Esprima because I noticed there was only one active maintainer now. If my current day-to-day job let me sacrifice some time I can solve all issues quickly. Except I can't do any PR. So if this project want my help, you can throw any issue you want at me and I can solve it for you.

**Comment by ariya** [comment] 2017-03-28 14:54
@nowindowsowrking Start a thread "How I can help" in the [mailing-list](http://groups.google.com/group/esprima). That way, we can keep every issue here from off-topic side discussions.

**Comment by nowindowsowrking** [comment] 2017-03-30 06:42
@ariya I did that 2 days ago! However. I discovered I just scratched the surface with this temporary solution. You need to add `CallExpression`, `TaggedTemplateExpression`, etc too, as well as a few keywords. 
`this`, `true`, `super` etc.  I found out it's best to point out to a live demo illustrating the solution on the various issues so you understand my thinking better. So just now I'm in the middle of creating a demo parser from scratch that will illustrate this. Give or take a few days and I'm done.

**Comment by nowindowsowrking** [comment] 2017-04-02 03:31
@ariya @mikesherov No response on the mailing list last 5 days, so I back out from helping on this project. Good knews is that I discovered around 300 - 400 defects, so I will consecutively open issue tickets regarding this matter.

**Comment by mikesherov** [comment] 2017-04-02 11:58
@nowindowsowrking that's certainly your own decision whether to submit pull requests or just issues, and we'll appreciate whatever contributions you give, but I have told you at least 4 times how you can help.

In case you missed it, I'll try one last time: Rather than theorizing how to make Esprima faster, nor pasting the solutions to issues in comments, you should:

1. File an issue describing a concrete issue.
2. Propose a pull request resolving the issue.
3. Ensure there are no regressions.
4. Add a test showing the defect is resolved.
5. If the fix is performance related, show the results of benchmark tests proving the fix.
6. Allow Ariya and I time to provide feedback on the PR.
7. Get your PR merged in.
8. Repeat.

I'm not sure how else to be more clear about that.

**Comment by nowindowsowrking** [comment] 2017-04-03 03:45
@mikesherov  Seems like you missed something, so back to school. Normally a developer has his own ideas on how the code should work. Or there is a kind of community behind it. And many places there also exist FAQ. So for a dev that want to contribute, he need to know the other devs thoughts. Devs that has been on the project for a long time. 
Example on this are TS, React, Jquery. One of the rules before comitting anything is to discuss how it should be implemented, if that kind of features are needed etc. E.g. TS doesn't allow any PR actually before this has been discussed into details.

And that is how it works in all companies as well. They starting out with a draft, gather the team and discuss. I have been in this industry the last 25 years. So I know.

I shortened this lesson now, but that is basic. So I thought a person who wanted to help out on Esprima project shouldn't just dive right in, push a PR even it's needed or not or maybe break another PR that is in a process, or something else that another dev is working on. Or something that isn't needed at all. 
That is what you pointed out now with your bulleted list.

And you also seem to be mistaken with your claim when you wrote `Rather than theorizing how to make Esprima faster, nor pasting the solutions to issues in comments,`

To comments up @ariya wrote 6 days ago:  `Start a thread "How I can help" in the mailing-list. `

So that what's I did. Nothing about performance etc if you have read that thread. Pure questions about the Esprima code base. Things that is obviously necessary for an outsider to know before jumping in. Things that is "normal" to discuss in forums. As pointed out at the top of the comment.

But once again. I understand that is not the norm with Esprima, because no replies after 6 days. Meaning lack of interest of another contributer. 

Short. Good luck with this project! I understand why there are no contributers on it.

**Closed** 2017-04-03 06:00 UTC

**Comment by mikesherov** [comment] 2017-04-03 10:31
It's ironic you mentioned jQuery, because I was part of the jQuery team as well. And the contribution process was similar there. I too have been in the industry, but only for 15 years, so I guess I still have something to learn as do we all.

I've never contributed to the Esprima mailing list, but one rule I know is to not expect immediate response. Esprima is an all volunteer project, and so sometimes it takes a few days when a large post is written. Sorry it took six days!

For issues that you posted on the issue tracker, particularly ones that I knew something about, I tried to respond helpfully, suggesting that you submit patches for the issues we were discussing, like re: curlyStack, after having discussed why the proposed solution might not work. I'm not sure how I could've been more helpful to you, but I'm sorry it came to this. Best of luck in your other endeavors!

**Comment by nowindowsowrking** [comment] 2017-04-04 06:55
@mikesherov it's ok. I left this project mainly because of the code structure and the complexity of solving even simple issues. So I developed my own parser the last 3 days. It's around 12 times faster then esprima and supports TC39 tests. I will push it one day so you can see how esprima could have been. Good luck to you too for the future. Take care!
