### ISSUE TITLE
parenthesised destructructuring

### ISSUE THREAD

**Issue by nowindowsowrking** [jquery/esprima#1801] opened 2017-03-26 23:58 UTC
Bindings should not have parenthesis around them.

### Steps to reproduce

```js
esprima.parse('({a}) = 0;')
esprima.parse('([a]) = 0;')
```

### Expected output
Should throw an error

### Actual output
Parses an AST

**Comment by ariya** [comment] 2017-03-27 01:45
Duplicate of #1164.

**Closed by ariya** 2017-03-27 01:45 UTC
