### ISSUE TITLE
incorrectly disallows `in` expressions in function-bodied arrows in for statement initialisers

### ISSUE THREAD

**Issue by lydell** [jquery/esprima#1793] opened 2017-03-25 15:53 UTC
### Steps to reproduce
```js
esprima.parse('for(()=>{a in b};;);')
```

### Expected output
```
Script {
  type: 'Program',
  body: 
   [ ForStatement {
       type: 'ForStatement',
       init: 
        ArrowFunctionExpression {
          type: 'ArrowFunctionExpression',
          id: null,
          params: [],
          body: 
           BlockStatement {
             type: 'BlockStatement',
             body: 
              [ ExpressionStatement {
                  type: 'ExpressionStatement',
                  expression: 
                   BinaryExpression {
                     type: 'BinaryExpression',
                     operator: 'in',
                     left: Identifier { type: 'Identifier', name: 'a' },
                     right: Identifier { type: 'Identifier', name: 'b' } } } ] },
          generator: false,
          expression: false,
          async: false },
       test: null,
       update: null,
       body: EmptyStatement { type: 'EmptyStatement' } } ],
  sourceType: 'script' }
```

### Actual output
```
Error: Line 1: Unexpected token in
    at ErrorHandler.constructError (/home/lydell/forks/esprima/dist/esprima.js:5045:22)
    at ErrorHandler.createError (/home/lydell/forks/esprima/dist/esprima.js:5061:27)
    at Parser.unexpectedTokenError (/home/lydell/forks/esprima/dist/esprima.js:1990:39)
    at Parser.throwUnexpectedToken (/home/lydell/forks/esprima/dist/esprima.js:2000:21)
    at Parser.consumeSemicolon (/home/lydell/forks/esprima/dist/esprima.js:2295:23)
    at Parser.parseLabelledStatement (/home/lydell/forks/esprima/dist/esprima.js:4058:19)
    at Parser.parseStatement (/home/lydell/forks/esprima/dist/esprima.js:4151:97)
    at Parser.parseStatementListItem (/home/lydell/forks/esprima/dist/esprima.js:3412:31)
    at Parser.parseFunctionSourceElements (/home/lydell/forks/esprima/dist/esprima.js:4224:29)
    at Parser.parseAssignmentExpression (/home/lydell/forks/esprima/dist/esprima.js:3304:56)
```

### Relevant references
shapesecurity/shift-parser-js#348

**Comment by nowindowsowrking** [comment] 2017-03-26 00:41
@lydell If this is urgent and if you can't wait until @ariya have solved this bug, you can solve it yourself if you replace [this line](https://github.com/jquery/esprima/blob/master/src/parser.ts#L1706-L1707) with this code.  

```js
let body;
if ( this.match('{')) {
    const previousAllowIn = this.context.allowIn;
    this.context.allowIn = true;
    body = this.parseFunctionSourceElements();
    this.context.allowIn = previousAllowIn;
} else {
    body = this.isolateCoverGrammar(this.parseAssignmentExpression);
}
```

**Comment by mikesherov** [comment] 2017-03-26 01:13
@nowindowsowrking, any chance you can submit a PR with the fix and some new tests? It seems like you have a good grasp of the codebase, we'd appreciate some more solid contributions to the codebase.

**Comment by nowindowsowrking** [comment] 2017-03-26 01:26
@mikesherov I will open a new thread in the mailing list. We can discuss there. Because I discovered a lot of things that I need to understand before I can move on to PR etc.

**Comment by mikesherov** [comment] 2017-03-26 01:54
I don't get it? Didn't you just post a fix for this issue in a comment above? I'm not asking you to rewrite the entire codebase, I'm just wondering if you'd like to submit a patch to fix bug being reported.

**Comment by nowindowsowrking** [comment] 2017-03-26 02:01
@mikesherov I posted a fix yes, but at ATM I can't post a PR from my computer used in my office work. No plans to rewrite the code base, but fixing that led me to other issues. So I decided to go for an solution that solve all open issue tickets if possible. In that case I got questions.

**Comment by mikesherov** [comment] 2017-03-26 02:37
> So I decided to go for an solution that solve all open issue tickets if possible. 

Your PR is not likely to be accepted if it is too large and attempts to fix too many things at once. As I mentioned before, if you'd really like to help out, filing specific bugs and submitting PRs for those gives us a chance to review the code in isolation and establishs trust and helps us all set a path forward together.

In the case that you feel you can speed up the scanner class, please do so! File a bug, explain how you intend on addressing it, post benchmarks, and fix.

Large scale all at once rewrites are not likely to be accepted.

**Comment by nowindowsowrking** [comment] 2017-03-26 02:53
That was one of the point why I asked something on the mailing list. Getting an overview and take things step by step. Offering a giant PR gains nothing. Unseen bugs will allways occur even you want or not if you do that. So my idea was just to get a understanding and hear the thoughts from the people and take it from there.  I also noticed @ariya like to have a issue ticket first before any PR.

**Comment by nowindowsowrking** [comment] 2017-03-26 03:51
@mikesherov @ariya I managed to make a PR, but discovered that this build system is not compat with Windows. So when I tried to create a test, I couldn't. Or I could, but had too do it manually. And also location tracker data differs from a Unix / Mac based computer vs a Windows computer. This related to mostly all Expression tests. At least on my laptop with windows 10.

So I then ignored that, but still couldn't create an test. Further. Paths issues as well on Windows and some other crazy things.

Too much hassle for me this one. So I'm back to only reporting issues. Good luck with Esprima!

**Comment by ariya** [comment] 2017-03-26 04:57
It's not true that Windows can't be used for Esprima development (I'm myself using a ThinkPad). We even have a CI run for Windows, see such an output at e.g. https://ci.appveyor.com/project/ariya/esprima/build/557, including running test suite with IE 11.

**Comment by nowindowsowrking** [comment] 2017-03-26 07:21
@ariya Ok. I believe you!  After cloning the repo and installed the depenencies, I tried this first: 
`npm run test` and ended up with 

```js

> esprima@4.0.0-dev check-version C:\xampp4\htdocs\esprima
> node test/check-version.js

Getting the canonical library version...
Library version is 4.0.0-dev
Checking package.json ...

> esprima@4.0.0-dev tslint C:\xampp4\htdocs\esprima
> tslint src/*.ts


> esprima@4.0.0-dev code-style C:\xampp4\htdocs\esprima
> tsfmt --verify src/*.ts && tsfmt --verify test/*.js

src/*.ts does not exist. process abort.
```

No `.ts` file found. But at least `94` tests was running from the api test. No fixtures. Other errors is that the `fixture.js` in dist folder is not found. Not sure if there should be any `fixture.js` in the dist folder, or if the path is wrong.  Anyway. I gave it up.

**Comment by ariya** [comment] 2017-03-30 02:02
From the grammar:
```
ConciseBody[In]:
    [ lookahead ≠ { ]  AssignmentExpression[?In, ~Yield, ~Await]
    {  FunctionBody[~Yield, ~Await]  }
```
Apparently, _[In]_ for the first production is conditional, while it's not the case for the second one.

The root cause of the problem is because currently Esprima parser does not handle the second production correctly.

**Closed** 2017-03-30 12:10 UTC
Labels: defect
